# Generated by Django 4.2 on 2023-04-22 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jacob', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
