# Generated by Django 4.2 on 2023-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jacob", "0011_role_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fio",
            field=models.CharField(default="?", max_length=30),
        ),
    ]
