# Generated by Django 4.2 on 2023-05-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jacob", "0014_task_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="less",
            name="role",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="jacob.role"
            ),
        ),
    ]
