# Generated by Django 4.2 on 2023-06-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jacob", "0018_userprofile_virtual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="res",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="they", to="jacob.role"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jacob.role",
            ),
        ),
        migrations.CreateModel(
            name="Wish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mywish", models.CharField(default="?", max_length=80)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jacob.project"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jacob.role"
                    ),
                ),
            ],
        ),
    ]
