# Generated by Django 4.2 on 2023-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jacob", "0020_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="mygrade",
            field=models.CharField(
                choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3", "3")],
                default="0",
                max_length=2,
            ),
        ),
    ]
