# Generated by Django 4.2 on 2023-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0015_less_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='load',
            field=models.IntegerField(default=0),
        ),
    ]
