# Generated by Django 4.2 on 2023-05-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jacob', '0016_alter_load_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='less',
            name='load',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='load',
            field=models.IntegerField(default=0),
        ),
    ]
